### ISSUE TITLE
A collection of minor issues

### ISSUE THREAD

**Issue by rok-cesnovar** [bstatcomp/project-cpath#2]
Here I will collect all the minor issues we need to resolve before making this public: 

- [x] Rscript in /tests/*.R currently dont work without RStudio

- [x] cleanup the old CPI_*.stan files

- [x] dont ship the *.rds containing the Rstan model, currently you need to manually delete it if you want it to work on Ubuntu after clone

- [x] use of `\\` in `sample_from_exe_new` fails of Ubuntu

- [x] small copy/paste error for `== unix`
```
if (my_os == "unix") {
    mod <- paste0("./bin/generalized_logistic_model/Win64/",
```

should be

```
if (my_os == "unix") {
    mod <- paste0("./bin/generalized_logistic_model/Linux/",
```

- [ ] For unix: make sure that folders exist before trying to write a file in it. I got an error creating `/tmp/RtmpOjyFI8/outb7ca.csv` because `/tmp/RtmpOjyFI8/` did not exist. Similar for `./tests/generalized_logistic_model/saved_samples/test2_Rstan_niter2000.rds` because `saved_samples` did not exist.

**Comment by gregorp90** [comment]
Check the last bullet point again -- why does the temporary folder not exist? Does it get deleted somewhere during the main function execution?

**Comment by rok-cesnovar** [comment]
The last bullet point was my mistake, I had some access issues with the AMD GPU.
